### ISSUE TITLE
Removing/Blocking txt in EMWIN reception

### ISSUE THREAD

**Issue by ZL1LAC** [JVital2013/goestools-win#3]
Any change you can add this function to the Windows version?

config for reference
```
[[handler]]
type = "text"
origin = "other"
directory = "./text"
filename = "{time:%Y%m%dT%H%M%SZ}_{filename}"
json = false
exclude_txt = true
```

**Comment by JVital2013** [comment]
Thanks for the request!

I pulled @tmbates12's original PR for this from https://github.com/pietern/goestools/pull/79 and merged it into the Windows port. It's available as of version 1.0.5, which I just released.

**This is a great example of the type of issue I will consider addressing, and I will reference back to this request in the future.** Typically, I will not address issues that are not windows-specific. I want to minimize deviation from Goestools for Linux to avoid letting this project evolve into something it isn't. 

However, this request [falls squarely into my general requirements for non-windows specific fixes](https://github.com/JVital2013/goestools-win#about-pull-requests):

- There is a PR for this functionality on the original goestools project that has not been rejected
- The patch is vetted to be stable
- The patch is either "generally accepted" by a lot of people, or is a new patch necessary to fix issues with the current HRIT transmission

Thanks again!
